package model;

import java.util.Random;

/**
 * Row of GenerationMatrix.
 * Contain Target with parameters for the generation / validation of test data.
 */
public class GenerationMatrixRow {

    /**
     * Test target used to generate test records data (SMS & Voice) from/to him,
     * and records with any mention about this target
     */
    private Target target;
    /**
     * count of 'from target number' records
     */
    private int fromNumberCount;
    /**
     * count of 'to target number' records
     */
    private int toNumberCount;
    /**
     * count of records with 'target phone' mention in text message
     */
    private int numberMention;
    /**
     * count of records with 'target keyword' mention in text message
     */
    private int keywordMention;
    /**
     * count of records with 'target name' mention in text message
     */
    private int nameMention;
    /**
     * count of records without any target mention, random records
     */
    private int withoutHitMention;

    /**
     * Row of GenerationMatrix.
     * Contain Target with parameters for the generation / validation of test data.
     * @param target Target
     */
    GenerationMatrixRow(Target target) {
        this.target = target;

        Random random = new Random();
        this.fromNumberCount = random.nextInt(2);
        this.toNumberCount = random.nextInt(2);
        this.numberMention = random.nextInt(2);
        this.keywordMention = random.nextInt(2);
        this.nameMention = random.nextInt(2);
        this.withoutHitMention = random.nextInt(5);
    }

    public Target getTarget() {
        return target;
    }

    public void setTarget(Target target) {
        this.target = target;
    }

    public int getFromNumberCount() {
        return fromNumberCount;
    }

    public void setFromNumberCount(int fromNumberCount) {
        this.fromNumberCount = fromNumberCount;
    }

    public int getToNumberCount() {
        return toNumberCount;
    }

    public void setToNumberCount(int toNumberCount) {
        this.toNumberCount = toNumberCount;
    }

    public int getNumberMention() {
        return numberMention;
    }

    public void setNumberMention(int numberMention) {
        this.numberMention = numberMention;
    }

    public int getKeywordMention() {
        return keywordMention;
    }

    public void setKeywordMention(int keywordMention) {
        this.keywordMention = keywordMention;
    }

    public int getNameMention() {
        return nameMention;
    }

    public void setNameMention(int nameMention) {
        this.nameMention = nameMention;
    }

    public int getWithoutHitMention() {
        return withoutHitMention;
    }

    public void setWithoutHitMention(int withoutHitMention) {
        this.withoutHitMention = withoutHitMention;
    }

    /**
     * Return the total number of records, that should be generated by the current GenerationMatrixRow
     * @return Total number of records
     */
    public int getTotalRecords() {
        int totalRecords = 0;

        totalRecords += fromNumberCount;
        totalRecords += toNumberCount;
        totalRecords += numberMention;
        totalRecords += keywordMention;
        totalRecords += nameMention;
        totalRecords += withoutHitMention;

        return totalRecords;
    }

    /**
     * Return the total number of records with target HIT, that should be generated by the GenerationMatrixRow.
     * Record with Target HIT: it mean that this record 'from/to' target phone.
     * @return Return the total number of records with target HIT
     */
    public int getTotalRecordsHit() {
        int totalRecordsHit = 0;

        totalRecordsHit += fromNumberCount;
        totalRecordsHit += toNumberCount;

        return totalRecordsHit;
    }

    /**
     * Return the total number of records with target MENTION, that should be generated by the GenerationMatrixRow.
     * Record with Target MENTION: it mean that this record contain any value of: target phone, target name, target keyword
     * @return Return the total number of records with target HIT
     */
    public int getTotalRecordsMention() {
        int totalRecordsMention = 0;

        totalRecordsMention += numberMention;
        totalRecordsMention += keywordMention;
        totalRecordsMention += nameMention;

        return totalRecordsMention;
    }
}
