package model;

import java.util.Random;

/**
 * Row of GenerationMatrix.
 * Contain Target with parameters for the generation / validation of test data.
 */
public class GenerationMatrixRow {

    private Target target;
    private int fromNumberCount;
    private int toNumberCount;
    private int fromNumberMention;
    private int toNumberMention;
    private int keywordMention;
    private int nameMention;
    private int withoutHitMention;

    /**
     * Row of GenerationMatrix.
     * Contain Target with parameters for the generation / validation of test data.
     * @param target Target
     */
    GenerationMatrixRow(Target target) {
        this.target = target;

        Random random = new Random();
        this.fromNumberCount = random.nextInt(2);
        this.toNumberCount = random.nextInt(2);
        this.fromNumberMention = random.nextInt(2);
        this.toNumberMention = random.nextInt(2);
        this.keywordMention = random.nextInt(2);
        this.nameMention = random.nextInt(2);
        this.withoutHitMention = random.nextInt(5);
    }

    public Target getTarget() {
        return target;
    }

    public void setTarget(Target target) {
        this.target = target;
    }

    public int getFromNumberCount() {
        return fromNumberCount;
    }

    public void setFromNumberCount(int fromNumberCount) {
        this.fromNumberCount = fromNumberCount;
    }

    public int getToNumberCount() {
        return toNumberCount;
    }

    public void setToNumberCount(int toNumberCount) {
        this.toNumberCount = toNumberCount;
    }

    public int getFromNumberMention() {
        return fromNumberMention;
    }

    public void setFromNumberMention(int fromNumberMention) {
        this.fromNumberMention = fromNumberMention;
    }

    public int getToNumberMention() {
        return toNumberMention;
    }

    public void setToNumberMention(int toNumberMention) {
        this.toNumberMention = toNumberMention;
    }

    public int getKeywordMention() {
        return keywordMention;
    }

    public void setKeywordMention(int keywordMention) {
        this.keywordMention = keywordMention;
    }

    public int getNameMention() {
        return nameMention;
    }

    public void setNameMention(int nameMention) {
        this.nameMention = nameMention;
    }

    public int getWithoutHitMention() {
        return withoutHitMention;
    }

    public void setWithoutHitMention(int withoutHitMention) {
        this.withoutHitMention = withoutHitMention;
    }

    /**
     * Return the total number of records, that should be generated by the current GenerationMatrixRow
     * @return Total number of records
     */
    public int getTotalRecords() {
        int totalRecords = 0;

        totalRecords += fromNumberCount;
        totalRecords += toNumberCount;
        totalRecords += fromNumberMention;
        totalRecords += toNumberMention;
        totalRecords += keywordMention;
        totalRecords += nameMention;
        totalRecords += withoutHitMention;

        return totalRecords;
    }

    /**
     * Return the total number of records with target HIT, that should be generated by the GenerationMatrixRow.
     * Record with Target HIT: it mean that this record 'from/to' target phone.
     * @return Return the total number of records with target HIT
     */
    public int getTotalRecordsHit() {
        int totalRecordsHit = 0;

        totalRecordsHit += fromNumberCount;
        totalRecordsHit += toNumberCount;

        return totalRecordsHit;
    }

    /**
     * Return the total number of records with target MENTION, that should be generated by the GenerationMatrixRow.
     * Record with Target MENTION: it mean that this record contain any value of: target phone, target name, target keyword
     * @return Return the total number of records with target HIT
     */
    public int getTotalRecordsMention() {
        int totalRecordsMention = 0;

        totalRecordsMention += fromNumberMention;
        totalRecordsMention += toNumberMention;
        totalRecordsMention += keywordMention;
        totalRecordsMention += nameMention;

        return totalRecordsMention;
    }
}
